### ISSUE TITLE
Chat with Dad screen

### ISSUE THREAD

**Issue by justinjandoc** [PocketDad/pocket_dad#10]
Please do work for this task in a branch named issue-10

The chat feature is the second main feature of the app, accessible from the bottom tab next to the Tasks tab. There is a prompt from Dad telling the user to ask anything. The user can type a question or a topic into the chat box. The default text in the chat box is “Tell me a joke,” which is overwritten when the user starts typing. From this screen, the user can also save the chat contents for future reference. While on the chat feature, the Chat option on the bottom bar is highlighted.

**Comment by yongsungm** [comment]
![Image](https://github.com/PocketDad/app/assets/97987234/d5d1b294-3096-48a5-8d46-fbb2bb1883c4)
