### ISSUE TITLE
Choose Avatar screen

### ISSUE THREAD

**Issue by justinjandoc** [PocketDad/pocket_dad#2]
Please do work for this task in a branch named issue-2

The second onboarding screen would show immediately after, asking the user to select a Dad avatar from a set of images. There is also an option to randomize the avatar. The user must input the name fields and choose an avatar to proceed.

**Comment by yongsungm** [comment]
![Image](https://github.com/PocketDad/app/assets/97987234/ac0bf2d6-1fea-47b3-9545-f1965c9cc202)
