### ISSUE TITLE
Change Avatar screen

### ISSUE THREAD

**Issue by justinjandoc** [PocketDad/pocket_dad#3]
Please do work for this task in a branch named issue-3

To be done after "Choose Avatar screen" issue is completed (issue 2).

The Change Avatar page is accessible from the menu side tab. This allows the user to change the look of the Dad avatar, similar to the initial onboarding selection.

**Comment by yongsungm** [comment]
Similar to Choose Avatar


![Image](https://github.com/PocketDad/app/assets/97987234/7c544168-cef8-465e-ba6d-a82014721a1b)
