### ISSUE TITLE
Check-in/Home screen

### ISSUE THREAD

**Issue by justinjandoc** [PocketDad/pocket_dad#4]
Please do work for this task in a branch named issue-4

- When the app is opened, PocketDad greets you and reminds you of your current tasks.
- Scrollable list to show all tasks
- Blue denotes variables (current time, number of tasks, task names, etc)
- Green denotes content that may be adjusted (change what PocketDad calls you, change date system ie dd/mm/yy vs mm/dd/yy)
- Orange denotes buttons and other interactable elements (tap on task to open more details/be able to complete, select navbar section)
- Purple denotes that PocketDad’s avatar can be changed

**Comment by yongsungm** [comment]
Similar to Completed Tasks, but not completed




![Image](https://github.com/PocketDad/app/assets/98081482/f34219e6-91e3-4bd6-a267-9d6b25c71314)
