### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by justinjandoc** [PocketDad/pocket_dad#9]
Please do work for this task in a branch named issue-9

The settings pop-up page is accessible from the top title bar on the app. The settings menu will appear in the center of the screen and darken the surrounding area. The settings menu holds the user’s personal information, such as name and birthday. The user has the option to save and close.

**Comment by yongsungm** [comment]
![Image](https://github.com/PocketDad/app/assets/97987234/f2ac499d-1c3a-4d06-a67b-4b89405fc417)
